---
openapi: 3.0.0
info:
  title: Addition API
  version: 1.0.0
  description: Addition API implemented with OpenAPI generator
tags:
  - name: "Addition"
paths:
  /add/{firstNumber}:
    get:
      summary: Add Summary
      tags:
        - "Addition"
      description: Get the added value
      operationId: addTwoNumbers
      parameters:
        - in: path
          name: firstNumber
          description: "First Number to be added"
          required: true
          schema:
            type: integer
        - in: query
          name: secondNumber
          description: "Second Number to be added"
          required: true
          schema:
            type: integer
      responses:
        200:
          description: Success
          content:
            application/json:
              schema:
                type: integer
                properties:
                  message:
                    type: string
        400:
          description: "Required parameter is missing or invalid"
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
                    example: "Invalid Parameter"
        404:
          description: "Not found"
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
                    example: "Not found"



